# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBjMyAED5o4ASUGN_Vvn1Kl73keL9nn4
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_comparision(original,sobel,prewitt,canny):
    plt.figure(figsize=(12,10))
    #Original image
    plt.subplot(2,2,1)
    plt.imshow(original,cmap='gray')
    plt.title('Original grayscale Image')
    plt.axis('off')
    #sobel edge detection
    plt.subplot(2,2,2)
    plt.imshow(sobel,cmap='gray')
    plt.title('Sobel Edge Detection')
    plt.axis('off')
    #prewitt edge detection
    plt.subplot(2,2,3)
    plt.imshow(prewitt,cmap='gray')
    plt.title('Prewitt Edge Detection')
    plt.axis('off')
    #canny edge detection
    plt.subplot(2,2,4)
    plt.imshow(canny,cmap='gray')
    plt.title('Canny Edge Detection')
    plt.axis('off')
    plt.tight_layout()
    plt.show()

#1.read an image
img=cv2.imread('/content/drive/MyDrive/images/bird.jpeg',0)
if img is None:
  print('Image not found')
else:
  #......sobel operator......
  #gradient in x and y direction
  sobelX=cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
  sobelY=cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)
  #combine gradients
  sobel_combined=cv2.magnitude(sobelX,sobelY)
  #prewitt operator
  #defines kernels(px,py)
  kernelx=np.array(([1,1,1],[0,0,0],[-1,-1,-1]))
  kernely=np.array(([1,0,-1],[1,0,-1],[1,0,-1]))
  #Apply Kernal using filter 2D
  prewittx=cv2.filter2D(img, -1, kernelx)
  prewitty=cv2.filter2D(img, -1, kernely)
  #combine gradients
  prewitt_combined=prewittx+prewitty
  #canny edge detection
  canny_edges=cv2.Canny(img,100,200)
  #show comparision
  show_comparision(img,np.uint8(np.absolute(sobel_combined)), prewitt_combined, canny_edges)